### ISSUE TITLE
[GOAL] Support viewing of medium, multi-channel timeseries data

### ISSUE THREAD

**Issue by droumis** [holoviz/holoviews#6058]
#### Is your feature request related to a problem? Please describe.
Target use cases of stacked timeseries commonly utilize a significant number of lines and samples which requires aggregation or downsampling in order to send to the browser. Currently, due to performance limitations, the standard HoloViews+Bokeh approach to this visualization with `subcoordinate_y` is only useable with a small part of the typical data size range.

#### Describe the solution you'd like
Let's shoot to make it not only possible, but smooth/performant to visualize and interact with:
**Medium Size Dataset**: too big for browser but fits in memory. For instance, a data size target of 100 stacked traces, each with 1,000 (16 bit) samples per second for 10,000 seconds. That's one billion samples and about 2 GB.

### Medium Size
- [x] Step 1: Downsample1d operation should slice once if all elements in an NdOverlay share the same underlying DataFrame (implemented in #6059) [@philippjfr @Hoxbro]
- [x] Step 2: Allow HoloViews to operate directly on a DataFrame with an index #6061 [@philippjfr @Hoxbro]
- [x] Step 3: Use tsdownsample library for downsampling if available #6059 [@philippjfr @Hoxbro]
- [ ] Step 4: [Add HoloViews' index support to hvPlot](https://github.com/holoviz/hvplot/issues/1292) [@maximlt]

## Notes for Medium Size:
- @philippjfr suggested that our implementation of LTTB downsampling would not scale sufficiently well for large datasets. This suggestion is backed up by comments in the [plotly resampler](https://github.com/predict-idlab/plotly-resampler/blob/2b79498eaa79cba891310dfcec3860936af3207b/plotly_resampler/aggregation/aggregators.py#L46): "for large datasets, [LTTB] can be much slower than other algorithms (e.g. MinMax) due to the higher cost of calculating the areas of triangles...`LTTB` doesn't scale super-well when moving to really large datasets, so when dealing with more than 1 million samples, you might consider using [`MinMaxLTTB`][aggregation.aggregators.MinMaxLTTB]"
- So either we could try an implementation of MinMaxLTTB (or even rely on the rust implementation of [tsdownsample](https://github.com/predict-idlab/tsdownsample) as plotly does - note, the author of tsdownsample [had offered to help](https://github.com/holoviz/holoviews/issues/2934#issuecomment-1367950689)!), ...
- ~~or we could try to get datashader to play nicely with `subcoordinate_y` while retaining all the niceties of standard Bokeh interactivity. If we go with Datashader, this would likely entail passing the scale and offset for each trace into the pre-Datashader rendering pipeline step.~~
- Update: Implement HoloViews' use of indexing for single shot slicing of wide df (big performance impact) and then use minmaxLTTB (less of a performance impact).

**Comment by droumis** [comment]
After talking with @philippjfr, the updated task is to first try to utilize tsdownsample directly (if it is available). Then we'll have LTTB and MinMaxLTTB available to us and we can check if this is sufficiently performant for our use cases. If not, we can then explore other options with Datashader.

**Comment by philippjfr** [comment]
Note that the precise downsampling implementation doesn't seem to matter much at all because most of the time is dominated by the slicing step, i.e. selecting the data within the viewport.

**Comment by philippjfr** [comment]
Having played with it some more I think the only way to support this workflow better is to add in an optimization for wide dataframes. Specifically if you create an NdOverlay of Curve elements from a DataFrame with columns A, B, C we need to make sure that all three Curve elements share the same underlying DataFrame, and the downsample operation should detect that, slice the DataFrame based on the current viewport and then apply the downsampling to that pre-sliced data. This will massively speed up downsampling for large numbers of traces.

**Comment by philippjfr** [comment]
This is probably a pre-requisite to get the above mentioned workflows working well: https://github.com/holoviz/holoviews/pull/6061

**Comment by droumis** [comment]
The remaining task has to do with hvPlot, so I'll close this as the HoloViews aspects are largely completed
